# Generated by Django 4.2.4 on 2023-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='description',
        ),
        migrations.AddField(
            model_name='character',
            name='damage',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='hp',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
