# Generated by Django 4.2.4 on 2023-08-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0002_remove_character_description_character_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='armor',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='luck',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='magic_res',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
