# Generated by Django 4.2.4 on 2023-08-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0005_remove_character_armor_remove_character_magic_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='skill_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
