# Generated by Django 4.2.4 on 2023-08-30 17:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0006_character_skill_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
