# Generated by Django 4.2.4 on 2023-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0007_character_experience_points_alter_character_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='gold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
