# Generated by Django 4.2.4 on 2023-09-15 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0008_character_gold'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='last_purchase_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
