# Generated by Django 4.2.4 on 2023-10-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0010_character_magic_res_character_physical_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='collected_gold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='killed_monsters',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='killed_players',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
