# Generated by Django 4.2.4 on 2023-10-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0011_character_collected_gold_character_killed_monsters_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(choices=[('knight', 'Knight'), ('thief', 'Thief'), ('wizard', 'Wizard'), ('cleric', 'Cleric'), ('ranger', 'Ranger'), ('paladin', 'Paladin'), ('barbarian', 'Barbarian'), ('druid', 'Druid'), ('bard', 'Bard'), ('monk', 'Monk'), ('necromancer', 'Necromancer'), ('inquisitor', 'Inquisitor'), ('elementalist', 'Elementalist')], max_length=100),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='name',
            field=models.CharField(choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('orc', 'Orc'), ('halfling', 'Halfling'), ('centaur', 'Centaur'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('minotaur', 'Minotaur'), ('lizardfolk', 'Lizardfolk'), ('dragonborn', 'Dragonborn'), ('sylvari', 'Sylvari')], max_length=100),
        ),
    ]
