# Generated by Django 4.2.4 on 2023-10-16 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0013_alter_character_character_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('knight', 'Knight'), ('thief', 'Thief'), ('wizard', 'Wizard'), ('cleric', 'Cleric'), ('ranger', 'Ranger'), ('paladin', 'Paladin'), ('barbarian', 'Barbarian'), ('druid', 'Druid'), ('bard', 'Bard'), ('monk', 'Monk'), ('necromancer', 'Necromancer'), ('inquisitor', 'Inquisitor')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CharacterRace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('human', 'Human'), ('elf', 'Elf'), ('dwarf', 'Dwarf'), ('orc', 'Orc'), ('halfling', 'Halfling'), ('centaur', 'Centaur'), ('half-elf', 'Half-Elf'), ('half-orc', 'Half-Orc'), ('minotaur', 'Minotaur'), ('lizardfolk', 'Lizardfolk'), ('dragonborn', 'Dragonborn'), ('sylvari', 'Sylvari')], max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='sex',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='male', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.characterclass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='character_race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Team.characterrace'),
        ),
    ]
