# Generated by Django 4.2.4 on 2023-10-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0014_characterclass_characterrace_character_sex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterclass',
            name='name',
            field=models.CharField(choices=[('Knight', 'Knight'), ('Thief', 'Thief'), ('Wizard', 'Wizard'), ('Cleric', 'Cleric'), ('Ranger', 'Ranger'), ('Paladin', 'Paladin'), ('Barbarian', 'Barbarian'), ('Druid', 'Druid'), ('Bard', 'Bard'), ('Monk', 'Monk'), ('Necromancer', 'Necromancer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='characterrace',
            name='name',
            field=models.CharField(choices=[('Human', 'Human'), ('Elf', 'Elf'), ('Dwarf', 'Dwarf'), ('Orc', 'Orc'), ('Halfling', 'Halfling'), ('Centaur', 'Centaur'), ('Half-elf', 'Half-Elf'), ('Half-orc', 'Half-Orc'), ('Minotaur', 'Minotaur'), ('Lizardfolk', 'Lizardfolk'), ('Dragonborn', 'Dragonborn'), ('Sylvari', 'Sylvari')], max_length=100),
        ),
    ]
