# Generated by Django 4.2.4 on 2023-11-02 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Team', '0016_alter_character_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='constitution',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='damage',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='dexterity',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='hp',
            field=models.PositiveIntegerField(default=200),
        ),
        migrations.AlterField(
            model_name='character',
            name='intelligence',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='luck',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='magic_res',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='physical_res',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='strength',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='character',
            name='wisdom',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
