# Generated by Django 4.2.4 on 2023-08-27 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField()),
                ('enemy_class', models.CharField(max_length=100)),
                ('enemy_race', models.CharField(max_length=100)),
                ('hp', models.PositiveIntegerField()),
                ('damage', models.PositiveIntegerField()),
            ],
        ),
    ]
