# Generated by Django 4.2.4 on 2023-08-28 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots_Farm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='armor',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='constitution',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='dexterity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='intelligence',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='luck',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='magic_res',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='strength',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='wisdom',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
