# Generated by Django 4.2.4 on 2023-08-29 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bots_Farm', '0002_enemy_armor_enemy_constitution_enemy_dexterity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enemy',
            name='armor',
        ),
        migrations.RemoveField(
            model_name='enemy',
            name='magic_res',
        ),
    ]
