# Generated by Django 4.2.4 on 2023-09-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots_Farm', '0004_enemy_magic_res_enemy_physical_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='max_exp',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='max_gold',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='enemy',
            name='min_exp',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enemy',
            name='min_gold',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
