# Generated by Django 4.2.4 on 2023-10-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bots_Farm', '0005_enemy_max_exp_enemy_max_gold_enemy_min_exp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='battle_duration',
            field=models.PositiveIntegerField(default=60),
        ),
    ]
