# Generated by Django 4.2.4 on 2023-09-05 09:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('hp', models.IntegerField(default=0)),
                ('damage', models.IntegerField(default=0)),
                ('strength', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('luck', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
            ],
        ),
    ]
