# Generated by Django 4.2.4 on 2023-09-11 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('main hand', 'Main Hand'), ('off hand', 'Off Hand'), ('head', 'Head'), ('shoulder', 'Shoulder'), ('chest', 'Chest'), ('hands', 'Hands'), ('feet', 'Feet'), ('neck', 'Neck'), ('cape', 'Cape'), ('ring', 'Ring'), ('charm', 'Charm')], max_length=20),
        ),
    ]
