# Generated by Django 4.2.4 on 2023-09-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_alter_item_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.CharField(choices=[('Common', 'Common'), ('Uncommon', 'Uncommon'), ('Rare', 'Rare'), ('Legendary', 'Legendary')], default='Common', max_length=20),
        ),
    ]
