# Generated by Django 4.2.4 on 2023-09-14 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0005_item_rarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=1),
        ),
    ]
