# Generated by Django 4.2.4 on 2023-10-05 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_item_magic_res_item_physical_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='enhancement_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='enhancement_level',
            field=models.IntegerField(default=0, max_length=20),
        ),
    ]
