# Generated by Django 4.2.4 on 2023-10-05 09:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0008_item_enhancement_cost_item_enhancement_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='enhancement_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
