# Generated by Django 4.2.4 on 2023-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0009_alter_item_enhancement_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='constitution',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='damage',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='luck',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='wisdom',
            field=models.IntegerField(default=1),
        ),
    ]
