# Generated by Django 4.2.4 on 2023-10-05 13:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0010_alter_item_constitution_alter_item_damage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='enhancement_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
