# Generated by Django 4.2.4 on 2023-10-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0011_alter_item_enhancement_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='base_constitution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_damage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_enhancement_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_luck',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_magic_res',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_physical_res',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='base_wisdom',
            field=models.IntegerField(default=1),
        ),
    ]
