# Generated by Django 4.2.4 on 2023-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0012_item_base_constitution_item_base_damage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='shop_type',
            field=models.CharField(choices=[('blacksmith', 'Blacksmith'), ('jeweler', 'Jeweler'), ('carpentry shop', 'Carpentry Shop'), ('clothier', 'Clothier'), ('armorer', 'Armorer')], default='blacksmith', max_length=20),
        ),
    ]
