# Generated by Django 4.2.4 on 2023-10-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0013_item_shop_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_type',
            field=models.CharField(choices=[('Main Hand', 'Main Hand'), ('Off Hand', 'Off Hand'), ('Head', 'Head'), ('Shoulder', 'Shoulder'), ('Chest', 'Chest'), ('Hands', 'Hands'), ('Feet', 'Feet'), ('Neck', 'Neck'), ('Cape', 'Cape'), ('Ring', 'Ring'), ('Charm', 'Charm')], max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='shop_type',
            field=models.CharField(choices=[('Blacksmith', 'Blacksmith'), ('Jeweler', 'Jeweler'), ('Carpentry Shop', 'Carpentry Shop'), ('Clothier', 'Clothier'), ('Armorer', 'Armorer')], default='blacksmith', max_length=20),
        ),
    ]
