# Generated by Django 4.2.4 on 2023-09-05 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
