# Generated by Django 4.2.4 on 2023-09-05 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_inventoryitem_item_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_count',
        ),
    ]
