# Generated by Django 4.2.4 on 2023-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0003_remove_inventoryitem_item_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
