# Generated by Django 4.2.4 on 2023-09-05 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_remove_inventoryitem_item_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='category',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='item_type',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
