# Generated by Django 4.2.4 on 2023-09-11 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0006_remove_inventoryitem_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item_count',
        ),
    ]
