# Generated by Django 4.2.4 on 2023-10-09 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0009_remove_inventoryitem_damage_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='constitution',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='damage',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='dexterity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='enhancement_cost',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='enhancement_level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='hp',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='intelligence',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='level',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='luck',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='magic_res',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='name',
            field=models.CharField(default='Test', max_length=100),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='physical_res',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='rarity',
            field=models.CharField(default='Common', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='strength',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='wisdom',
            field=models.IntegerField(default=1),
        ),
    ]
