# Generated by Django 4.2.4 on 2023-10-09 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tavern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
